### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by F-36** [wave1822/redarcs-reader#1]
$ python3 readable.py PolandballCommunity_submissions
Traceback (most recent call last):
  File "/home/k/Downloads/readable.py", line 51, in <module>
    main(filename)
  File "/home/k/Downloads/readable.py", line 25, in main
    created_date = datetime.utcfromtimestamp(created_utc).strftime('%d/%m/%Y')
TypeError: 'str' object cannot be interpreted as an integer

or

$ python3 readable.py AnimatedPixelArt_comments
Traceback (most recent call last):
  File "/home/k/Downloads/readable.py", line 51, in <module>
    main(filename)
  File "/home/k/Downloads/readable.py", line 21, in main
    title = post['title']
KeyError: 'title'

EDIT: it's fixed.

**Comment by wave1822** [comment]
I updated the code so the "created_utc" is converted to an integer using "int()" before using it with "datetime.utcfromtimestamp()" I think this should fix you problem.

**Comment by wave1822** [comment]
About the second error this script is supposed to work only in submissions not comments.

**Comment by wave1822** [comment]
Hey you closed the issue I will assume it's fixed, but anyway I just come to say I made a script to format the comments file you mind to check it out?
